services:
  - type: web
    name: knu-mla-backend
    plan: free
    rootDir: backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: knu-mla-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: "*"

databases:
  - name: knu-mla-db
    plan: free
